src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Cocur\Slugify\Slugify;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @Vich\Uploadable()
 */
class Property
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @var String|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;
    /**
     * @var File|null
     *  * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_image",fileNameProperty="filename")
     * 
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10 , max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $chambres;

    /**
     * @ORM\Column(type="integer")
     */
    private $pieces;

    /**
     * @ORM\Column(type="integer")
     */
    private $etage;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255 ,nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *  * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="boolean" ,options={"default":false})
     */
    private $vendue = false;


    
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
    public function __construct()
    {
        $this->created_at = new DateTime() ;
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    public function getSlug() :string
    {
       return  $slugify = (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getChambres(): ?int
    {
        return $this->chambres;
    }

    public function setChambres(int $chambres): self
    {
        $this->chambres = $chambres;

        return $this;
    }

    public function getPieces(): ?int
    {
        return $this->pieces;
    }

    public function setPieces(int $pieces): self
    {
        $this->pieces = $pieces;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(int $etage): self
    {
        $this->etage = $etage;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }
    public function getPrixFormater(): ?string
    {
        return number_format($this->prix,0,'',' ') ;
    }


    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVendue(): ?bool
    {
        return $this->vendue;
    }

    public function setVendue(bool $vendue): self
    {
        $this->vendue = $vendue;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

	/**
	 * 
	 * @return File|null
	 */
	public function getImageFile() : ?File
              {
         		return $this->imageFile;
         	}
	
	/**
	 * 
	 * @param File|null $imageFile 
	 * @return self
	 */
	public function setImageFile(?File $imageFile): Property {
         		$this->imageFile = $imageFile;
                if ($this->imageFile instanceof UploadedFile) {
                    $this->updated_at = new DateTime('now');
                }
         		return $this;
         	}

	/**
	 * 
	 * @return String|null
	 */
	public function getFilename() : ?String
             {
         		return $this->filename;
         	}
	
	/**
	 * 
	 * @param String|null $filename 
	 * @return Property
	 */
	public function setFilename(?String $filename): self {
         		$this->filename = $filename;
         		return $this;
         	}

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('chambres')
            ->add('pieces')
            ->add('etage')
            ->add('prix')
            ->add('options',EntityType::class,[
                'class'=>Option::class,
                'required'=>false,
                'choice_label'=>'nom',
                'multiple'=>true
            ])
            ->add('imageFile',FileType::class,['required'=>false])
            ->add('city',null,['label'=>'Ville'])
            ->add('adresse')
            ->add('code_postal')
            ->add('vendue')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\RechercheBiens;
use App\Form\ContactType;
use App\Form\RechercheBiensType;

use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use PhpParser\Node\Expr\Cast\String_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request as HttpFoundationRequest;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @Var PropertyRepository
     */
    
    private $repository ;

    public function __construct(PropertyRepository $repository)
    {
        
         $this->repository= $repository;
    }

    /**
     * @Route("/biens", name="property.index")
     */
    public function index(PaginatorInterface $paginator ,HttpFoundationRequest $request): Response
    {
        $recherche= new RechercheBiens();
        $form= $this->createForm(RechercheBiensType::class,$recherche);
        $form->handleRequest($request);
        $properties = $paginator->paginate(
            $this->repository->findAllVIsibleQuery($recherche),
        $request->query->getInt('page',1),
        12
        );
    
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties'=>$properties ,
            'form' =>$form->createView()
        ]);
    }
    /** 
    * @Route("/biens/{slug}-{id}",name="property.show", requirements={"slug": "[a-z0-9\-]*"})
    */
    public function show(Property $property ,string $slug , Request $request,ContactNotification $notification):Response
    {

        if($property->getSlug()!==$slug)
        {
        return $this->redirectToRoute("property.show",[
            'id'=>$property->getId(),
            'slug'=>$property->getSlug()],301);
       }

       $contact=new Contact;
       $contact->setProperty($property);
       $form=$this->createForm(ContactType::class,$contact);
       $form->handleRequest($request);

       if($form->isSubmitted() && $form->isValid() ){
        $notification->notify($contact);
        $this->addFlash("succes","votre message a ete envoye avec succe");

        return $this->redirectToRoute("property.show",[
            'id'=>$property->getId(),
            'slug'=>$property->getSlug()]);
 
       }

   
        return $this->render("property/show.html.twig",[
            "property"=>$property,
            'current_menu' => 'properties',
            'form'=>$form->createView()
           ]);
        
   }

}

templates/property/_property.html.twig
<div class="card mb-4">
{% if property.filename %}
<img src=" {{vich_uploader_asset(property ,'imageFile')|imagine_filter('thumb')}}" alt="card-img-top" style="width: 100%;height:auto;">
{% else %}
<img src=" {{'/images/properties/empty.jpg' | imagine_filter('thumb')}}" alt="card-img-top" style="width: 100%;height:auto;">
{% endif %}
    <div class="card-body">
        <h5 class="card-title">
        <a href="{{ path('property.show',{ slug: property.slug , id:property.id}) }}">
        {{ property.title}}
        </a>
        </h5>
        <p class="card-text">{{ property.surface}} m² - {{ property.city}} ({{ property.title}} )</p>
        <div class="text-primary" style="font-size:2rem ;font-weight:bold ;">
        {{ property.prixFormater}} Fcfa
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nos biens
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="row align-items-end">
                <div class="col">
                    {{ form_row(form.prixMax) }}
                </div>
                <div class="col">
                    {{ form_row(form.surfaceMin) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <button class="btn btn-primary">
                        Rechercher
                    </button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4 text-center">
        <h1>
            voir nos biens
        </h1>
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            {% for message in app.flashes("succes") %}
         <div class="alert alert-success">
            {{ message }}
         </div>
      {% endfor %}
      {% if not form.vars.valid %}
      <div class="alert alert-danger">
      Verirfier bien les informaions que vous entrez
      </div>
      {% endif %}
            <div class="row">
                <div class="col-md-8">
    {% if property.filename %}
<img src=" {{vich_uploader_asset(property ,'imageFile')|imagine_filter('medium')}}" alt="card-img-top" style="width: 100%;height:auto;">
{% else %}
<img src=" {{'/images/properties/empty.jpg' | imagine_filter('medium')}}" alt="card-img-top" style="width: 100%;height:auto;">
{% endif %}
                </div>
                <div class="col-md-4">
                    <h1>
                        {{ property.title }}
                    </h1>
                    <h2>
                        {{ property.pieces }}
                        pièces - 
                        {{ property.surface }}
                        m2
                    </h2>
                    <div class="text-primary" style="font-size: 4rem;font-weigth:bold;">
                        {{ property.prixformater }}
                        Fcfa 
                    </div>
                    <a href="#" class="btn-primary">
                        Contacter nous
                    </a>
                    <div id="contactForm" class="mt-4">
                    {{form_start(form)}}
                    <div class="row"
                    <div class="col">{{ form_row(form.firstname) }} </div>
                    <div class="col">{{ form_row(form.lastname) }} </div>
                    </div>
                    <div class="row"
                    <div class="col">{{ form_row(form.phone) }} </div>
                    <div class="col">{{ form_row(form.email) }} </div>
                    </div>
                    {{form_rest(form)}} 
                    <div class="form-group">
                   <button class="btn btn-primary">Envoyer</button>
                   </div>
                    {{form_end(form)}}
                </div>
            </div>
        </div>
    </div>
</div>
    <div class="container  mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="container  mt-8">
                <h2>
                    Caractèristiques
                </h2>
                <table class="table table-striped">
                    <tr>
                        <td>
                            surface habitable
                        </td>
                        <td>
                            {{ property.surface }}
                            m2
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Pièces
                        </td>
                        <td>
                            {{ property.pieces }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nombre de chambres
                        </td>
                        <td>
                            {{ property.chambres }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Etages
                        </td>
                        <td>
                            {{ property.etage }}
                        </td>
                    </tr>
                </table>
            </div>
           <div class="container  mt-4">
                <h2>
                    Spécificités
                </h2>
                <ul class="list-group">
                {% for option in property.options %}
                <li class="list-group-item">{{option.nom}}</li>
                {% endfor %}
                </ul>
        </div>
    </div> 
</div>
            {% endblock %}
            